name: Verify Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  verify-deployment:
    name: Verify Vercel URL Status
    runs-on: ubuntu-latest
    steps:
      - name: Verify Vercel URL Status
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://travelpad.vercel.app)
          echo "Received status code: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Deployment status is not 200!"
            exit 1
          fi
